name: Automated Unit Tests

on: 
  push: 
    branches:
      - main
  pull_request: 
    branches: 
      - main
      
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        
    - name: Test with Maven
      run: mvn test --batch-mode --no-transfer-progress
