name: Automated Unit Tests

on: 
  push: 
    branches:
      - main
  pull_request: 
    branches: 
      - main
      
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Install dependencies
        run: mvn clean install --batch-mode --no-transfer-progress
        
      - name: Run tests
        run: mvn test --batch-mode --no-transfer-progress
